// Generated by script/brand.ts. Do not edit directly.
export const PRODUCT_NAME = "ForeachCode"
export const PRODUCT_CLI = "foreachcode"
export const SERVER_READY_PREFIX = "ForeachCode server listening"
