// Generated by script/brand.ts. Do not edit directly.
declare const PRODUCT_BRAND_JSON: string
const PRODUCT_BRAND = JSON.parse(PRODUCT_BRAND_JSON) as { name: string; slug: string }
export const PRODUCT_NAME = PRODUCT_BRAND.name
export const PRODUCT_CLI = PRODUCT_BRAND.slug
export const SERVER_READY_PREFIX = "server listening on "
