import { mkdir } from "node:fs/promises"
import path from "node:path"
import { Brand } from "../packages/brand/src"

export const targetPaths = Object.freeze([
  "packages/brand/generated/brand.env",
  "packages/brand/generated/brand.json",
  "packages/sdk/js/src/brand.gen.ts",
])

export const staticTargetPaths = Object.freeze([
  "install",
  "packages/opencode/package.json",
  "packages/desktop/package.json",
  "packages/desktop/src/renderer/index.html",
  "packages/ui/src/assets/favicon/site.webmanifest",
  "packages/ui/src/theme/desktop-theme.schema.json",
  "packages/ui/src/theme/themes/opencode.json",
  "packages/app/index.html",
  "packages/opencode/bin/opencode",
  "packages/opencode/Dockerfile",
  "nix/opencode.nix",
  "packages/opencode/script/postinstall.mjs",
  "packages/ui/src/assets/favicon/favicon.svg",
  "packages/ui/src/assets/favicon/favicon-v3.svg",
  "packages/app/public/oc-theme-preload.js",
])

const root = path.resolve(import.meta.dir, "..")

function targets(base: string) {
  return [
    {
      path: targetPaths[0],
      content: [
        `PRODUCT_NAME=${Brand.name}`,
        `PRODUCT_SLUG=${Brand.slug}`,
        `PRODUCT_CLI=${Brand.cli}`,
        `PRODUCT_PROTOCOL=${Brand.protocol}`,
        `PRODUCT_DIRECTORY=${Brand.directory}`,
        `PRODUCT_DATABASE=${Brand.database}`,
        `PRODUCT_LOG=${Brand.log}`,
        `PRODUCT_DESKTOP_APP_ID=${Brand.desktopAppId}`,
        "",
      ].join("\n"),
    },
    {
      path: targetPaths[1],
      content: `${JSON.stringify(Brand, null, 2)}\n`,
    },
    {
      path: targetPaths[2],
      content: [
        "// Generated by script/brand.ts. Do not edit directly.",
        `export const PRODUCT_NAME = ${JSON.stringify(Brand.name)}`,
        `export const PRODUCT_CLI = ${JSON.stringify(Brand.cli)}`,
        `export const SERVER_READY_PREFIX = ${JSON.stringify(`${Brand.name} server listening`)}`,
        "",
      ].join("\n"),
    },
  ].map((target) => ({ ...target, absolute: path.join(base, target.path) }))
}

export async function generateBrandTargets(base = root) {
  await Promise.all(
    targets(base).map(async (target) => {
      await mkdir(path.dirname(target.absolute), { recursive: true })
      await Bun.write(target.absolute, target.content)
    }),
  )
}

export async function checkBrandTargets(base = root) {
  const checks = await Promise.all(
    targets(base).map(async (target) => {
      if (!(await Bun.file(target.absolute).exists())) return target.path
      if ((await Bun.file(target.absolute).text()) !== target.content) return target.path
    }),
  )
  return checks.filter((item) => item !== undefined)
}

async function staticTargets(base: string) {
  const install = await Bun.file(path.join(base, staticTargetPaths[0])).text()
  const opencode = await Bun.file(path.join(base, staticTargetPaths[1])).json()
  const desktop = await Bun.file(path.join(base, staticTargetPaths[2])).json()
  const html = await Bun.file(path.join(base, staticTargetPaths[3])).text()
  const manifest = await Bun.file(path.join(base, staticTargetPaths[4])).json()
  const schema = await Bun.file(path.join(base, staticTargetPaths[5])).text()
  const theme = await Bun.file(path.join(base, staticTargetPaths[6])).json()
  const appHtml = await Bun.file(path.join(base, staticTargetPaths[7])).text()
  const launcher = await Bun.file(path.join(base, staticTargetPaths[8])).text()
  const dockerfile = await Bun.file(path.join(base, staticTargetPaths[9])).text()
  const nix = await Bun.file(path.join(base, staticTargetPaths[10])).text()
  const postinstall = await Bun.file(path.join(base, staticTargetPaths[11])).text()
  const favicon = await Bun.file(path.join(base, staticTargetPaths[12])).text()
  const faviconV3 = await Bun.file(path.join(base, staticTargetPaths[13])).text()
  const themePreload = await Bun.file(path.join(base, staticTargetPaths[14])).text()

  const installBlock = `# brand:start\nAPP=${Brand.slug}\nPRODUCT_NAME=${Brand.name}\n# brand:end`
  const nextInstall = install.replace(/# brand:start[\s\S]*?# brand:end/, installBlock)
  const nextOpencode = { ...opencode, bin: { [Brand.cli]: "./bin/opencode" } }
  const nextDesktop = { ...desktop, author: { name: Brand.name } }
  delete nextDesktop.homepage
  const nextHtml = html.replace(/<title>.*?<\/title>/, `<title>${Brand.name}</title>`)
  const nextManifest = { ...manifest, name: Brand.name, short_name: Brand.name }
  const nextSchema = schema
    .replace(/"title":\s*".*?"/, `"title": "${Brand.name} Desktop Theme"`)
    .replace(/"description":\s*".*?"/, `"description": "A theme definition for the ${Brand.name} desktop application"`)
  const nextTheme = { ...theme, name: Brand.name }
  const nextAppHtml = appHtml.replace(/<title>.*?<\/title>/, `<title>${Brand.name}</title>`)
  const nextLauncher = launcher.replace(
    /\/\/ brand:start[\s\S]*?\/\/ brand:end/,
    [
      "// brand:start",
      `const productName = ${JSON.stringify(Brand.name)}`,
      `const productSlug = ${JSON.stringify(Brand.slug)}`,
      `const productCli = ${JSON.stringify(Brand.cli)}`,
      `const productDirectory = ${JSON.stringify(Brand.directory)}`,
      "// brand:end",
    ].join("\n"),
  )
  const nextDockerfile = dockerfile.replace(
    /# brand:start[\s\S]*?# brand:end/,
    [
      "# brand:start",
      `COPY dist/${Brand.slug}-linux-x64-baseline-musl/bin/${Brand.cli} /usr/local/bin/${Brand.cli}`,
      "",
      "FROM base AS build-arm64",
      `COPY dist/${Brand.slug}-linux-arm64-musl/bin/${Brand.cli} /usr/local/bin/${Brand.cli}`,
      "",
      "ARG TARGETARCH",
      "FROM build-${TARGETARCH}",
      `RUN ${Brand.cli} --version`,
      `ENTRYPOINT [${JSON.stringify(Brand.cli)}]`,
      "# brand:end",
    ].join("\n"),
  )
  const nextNix = nix.replace(
    /# brand:start[\s\S]*?# brand:end/,
    `# brand:start\n  product = ${JSON.stringify(Brand.slug)};\n  # brand:end`,
  )
  const nextPostinstall = postinstall.replace(
    /\/\/ brand:start[\s\S]*?\/\/ brand:end/,
    [
      "// brand:start",
      `const productName = ${JSON.stringify(Brand.name)}`,
      `const productSlug = ${JSON.stringify(Brand.slug)}`,
      `const productCli = ${JSON.stringify(Brand.cli)}`,
      "// brand:end",
    ].join("\n"),
  )
  const nextFavicon = favicon.replace(
    /<title id="title">.*? application icon<\/title>/,
    `<title id="title">${Brand.name} application icon</title>`,
  )
  const nextFaviconV3 = faviconV3.replace(
    /<title id="title">.*? application icon<\/title>/,
    `<title id="title">${Brand.name} application icon</title>`,
  )
  const nextThemePreload = themePreload.replace(
    /\/\/ brand:start[\s\S]*?\/\/ brand:end/,
    `// brand:start\n  var productSlug = ${JSON.stringify(Brand.slug)}\n  // brand:end`,
  )

  return [
    { path: staticTargetPaths[0], content: nextInstall },
    { path: staticTargetPaths[1], content: `${JSON.stringify(nextOpencode, null, 2)}\n` },
    { path: staticTargetPaths[2], content: `${JSON.stringify(nextDesktop, null, 2)}\n` },
    { path: staticTargetPaths[3], content: nextHtml },
    { path: staticTargetPaths[4], content: `${JSON.stringify(nextManifest, null, 2)}\n` },
    { path: staticTargetPaths[5], content: nextSchema },
    { path: staticTargetPaths[6], content: `${JSON.stringify(nextTheme, null, 2)}\n` },
    { path: staticTargetPaths[7], content: nextAppHtml },
    { path: staticTargetPaths[8], content: nextLauncher },
    { path: staticTargetPaths[9], content: nextDockerfile },
    { path: staticTargetPaths[10], content: nextNix },
    { path: staticTargetPaths[11], content: nextPostinstall },
    { path: staticTargetPaths[12], content: nextFavicon },
    { path: staticTargetPaths[13], content: nextFaviconV3 },
    { path: staticTargetPaths[14], content: nextThemePreload },
  ].map((target) => ({ ...target, absolute: path.join(base, target.path) }))
}

export async function generateStaticBrandTargets(base = root) {
  await Promise.all((await staticTargets(base)).map((target) => Bun.write(target.absolute, target.content)))
}

export async function checkStaticBrandTargets(base = root) {
  const checks = await Promise.all(
    (await staticTargets(base)).map(async (target) => {
      if ((await Bun.file(target.absolute).text()) !== target.content) return target.path
    }),
  )
  return checks.filter((item) => item !== undefined)
}

if (import.meta.main) {
  const check = process.argv.slice(2).includes("--check")
  if (!check) {
    await generateBrandTargets()
    await generateStaticBrandTargets()
    console.log(`Generated ${targetPaths.length + staticTargetPaths.length} brand targets.`)
    process.exit(0)
  }

  const stale = [...(await checkBrandTargets()), ...(await checkStaticBrandTargets())]
  if (stale.length === 0) {
    console.log("Brand targets are up to date.")
    process.exit(0)
  }

  console.error(`Brand targets are stale:\n${stale.map((item) => `- ${item}`).join("\n")}`)
  process.exit(1)
}
