import type { sessionExportEnglish } from "../i18n/session-export"

export function sessionHtmlLabels(t: (key: keyof typeof sessionExportEnglish) => string) {
  return {
    loading: t("session.export.html.loading"),
    failed: t("session.export.html.failed"),
    javascript: t("session.export.html.javascript"),
    subtitle: t("session.export.html.subtitle"),
    download: t("session.export.html.download"),
    empty: t("session.export.html.empty"),
    user: t("session.export.html.user"),
    assistant: t("session.export.html.assistant"),
    annotation: t("session.export.html.annotation"),
    questions: t("session.export.html.questions"),
    answer: t("session.export.html.answer"),
    selected: t("session.export.html.selected"),
    noAnswer: t("session.export.html.noAnswer"),
    awaitingAnswer: t("session.export.html.awaitingAnswer"),
    answerUnavailable: t("session.export.html.answerUnavailable"),
    rawInputOutput: t("session.export.html.rawInputOutput"),
    subagent: t("session.export.html.subagent"),
    viewTask: t("session.export.html.viewTask"),
    viewDetails: t("session.export.html.viewDetails"),
    close: t("session.export.html.close"),
    delegation: t("session.export.html.delegation"),
    taskResult: t("session.export.html.taskResult"),
    background: t("session.export.html.background"),
    subagentAwaiting: t("session.export.html.subagentAwaiting"),
    subagentUnavailable: t("session.export.html.subagentUnavailable"),
    reasoning: t("session.export.html.reasoning"),
    input: t("session.export.html.input"),
    output: t("session.export.html.output"),
    attachment: t("session.export.html.attachment"),
    unavailable: t("session.export.html.unavailable"),
    copy: t("session.export.html.copy"),
    copied: t("session.export.html.copied"),
    copyFailed: t("session.export.html.copyFailed"),
    details: t("session.export.html.details"),
    pending: t("session.export.html.pending"),
    running: t("session.export.html.running"),
    completed: t("session.export.html.completed"),
    error: t("session.export.html.error"),
    created: t("session.export.html.created"),
    exported: t("session.export.html.exported"),
  }
}
